[package]
name = "libtailscale"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { version = "0.4.17", default-features = false }
nix = "0.26.2"
thiserror = "1.0.39"

[dev-dependencies]
env_logger = "0.10.0"
